DROP EXTENSION IF EXISTS pg_rgi_fdw CASCADE;
CREATE EXTENSION pg_rgi_fdw;
CREATE SERVER IF NOT EXISTS rgi FOREIGN DATA WRAPPER pg_rgi_fdw;
CREATE FOREIGN TABLE IF NOT EXISTS kv_rgi (k bigint, v bigint) SERVER rgi;
